apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: {{deployment_name}}
  labels:
    # must have this label
    kalavai.job.name: {{deployment_name}}
spec:
  queue: default
  schedulerName: volcano
  plugins:
    env: []
    svc: ["--disable-network-policy=true"]
  policies: 
  - event: PodEvicted # Restart the job when a pod is evicted.
    action: RestartJob
  tasks:
  - replicas: 1   # One ps pod specified
    name: server
    template: # Definition of the ps pod
      metadata:
        annotations:
          # must have these annotations
          {{nouse_gputype}}
          {{use_gputype}}
        labels:
          role: leader
          kalavai.job.name: {{deployment_name}}
      spec:
        runtimeClassName: nvidia
        containers:
        - name: llamacpp-leader
          image: docker.io/bundenth/llamacpp-gpu:latest
          command:
          - sh
          - -c
          - |
            /workspace/build.sh server_gpu;
            /workspace/merge.sh --cpu-workers=/etc/volcano/cpu.host --gpu-workers=/etc/volcano/gpu.host --output=/workspace/all.host;
            HOSTS=`head /workspace/all.host`;
            cat /workspace/all.host;
            export WORKERS=$(/workspace/get_workers_address.sh --rpc_port={{rpc_port}} --rpc_servers="${HOSTS}")
            /workspace/run_api_server.sh \
              --repo_id={{repo_id}} \
              --model_filename={{model_filename}} \
              --local_dir=/cache \
              --port=8080 \
              --rpc_servers=$WORKERS \
              --extra='{{server_extra}}'
          env:
          - name: HF_TOKEN
            value: {{hf_token}}
          ports:
          - containerPort: 8080
            name: model-port
          resources:
            requests:
              cpu: {{cpus}}
              memory: {{memory}}Gi
              nvidia.com/gpu: {{gpus}}
            limits:
              cpu: {{cpus}}
              memory: {{memory}}Gi
              nvidia.com/gpu: {{gpus}}
          volumeMounts:
            - name: cache
              mountPath: /cache
        volumes:
        - name: cache
          persistentVolumeClaim:
            claimName: {{storage}}
        restartPolicy: Never
  - replicas: {{cpu_workers}}
    name: cpu
    policies:
    - event: TaskCompleted  # The job will be marked as completed when two worker pods finish tasks.
      action: CompleteJob
    template: # Definition of worker pods
      metadata:
        labels:
          kalavai.job.name: {{deployment_name}}
      spec:
        containers:
        - name: llamacpp-worker
          image: docker.io/bundenth/llamacpp-cpu:latest
          command:
          - sh
          - -c
          - |
            /workspace/build.sh cpu;
            /workspace/run_rpc_worker.sh --rpc_port={{rpc_port}}
          env:
          - name: HF_TOKEN
            value: {{hf_token}}
          resources:
            requests:
              cpu: {{cpus}}
              memory: {{memory}}Gi
            limits:
              cpu: {{cpus}}
              memory: {{memory}}Gi
        restartPolicy: Never
  - replicas: {{gpu_workers}}
    name: gpu
    policies:
    - event: TaskCompleted  # The job will be marked as completed when two worker pods finish tasks.
      action: CompleteJob
    template: # Definition of worker pods
      metadata:
        annotations:
          # must have these annotations
          {{nouse_gputype}}
          {{use_gputype}}
        labels:
          kalavai.job.name: {{deployment_name}}
      spec:
        runtimeClassName: nvidia
        containers:
        - name: llamacpp-worker
          image: docker.io/bundenth/llamacpp-gpu:latest
          command:
          - sh
          - -c
          - |
            /workspace/build.sh gpu;
            /workspace/run_rpc_worker.sh --rpc_port={{rpc_port}}
          env:
          - name: HF_TOKEN
            value: {{hf_token}}
          resources:
            requests:
              cpu: {{cpus}}
              memory: {{memory}}Gi
              nvidia.com/gpu: {{gpus}}
            limits:
              cpu: {{cpus}}
              memory: {{memory}}Gi
              nvidia.com/gpu: {{gpus}}
        restartPolicy: Never
