# Specs and examples: https://github.com/kubernetes-sigs/lws/blob/main/docs/examples/sample/README.md
apiVersion: leaderworkerset.x-k8s.io/v1
kind: LeaderWorkerSet
metadata:
  name: $deployment_name
  labels:
    # must have this label
    kalavai.lws.name: $deployment_name
spec:
  # number of copies for this deployment
  replicas: 1
  leaderWorkerTemplate:
    # how many workers (distributed nodes)
    size: 2
    workerTemplate:
      spec:
        containers:
        - name: nginx
          # docker image to use as base for each worker
          image: nginx:1.14.2
          # what resources each worker should have
          resources:
            limits:
              cpu: "100m"
              memory: "1Gi"
              nvidia.com/gpu: "1"
            requests:
              cpu: "50m"
              memory: "1Gi"
              nvidia.com/gpu: "1"
          ports:
          # what port to make available
          - containerPort: 8080