apiVersion: v1
kind: Service
metadata:
  name: $deployment_name-auto
  labels:
    kalavai.lws.name: $deployment_name
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    kalavai.lws.name: $deployment_name
    role: leader
  type: NodePort