apiVersion: leaderworkerset.x-k8s.io/v1
kind: LeaderWorkerSet
metadata:
  name: $deployment_name
  labels:
    # must have this label
    kalavai.lws.name: $deployment_name
spec:
  replicas: $replicas
  leaderWorkerTemplate:
    size: $num_workers
    restartPolicy: RecreateGroupOnPodRestart
    leaderTemplate:
      metadata:
        labels:
          role: leader
          kalavai.lws.name: $deployment_name
      spec:
        runtimeClassName: nvidia
        containers:
        - name: vllm-leader
          image: bundenth/ray-vllm:v1_1
          env:
          - name: HUGGING_FACE_HUB_TOKEN
            value: $hf_token
          command:
            - sh
            - -c
            - "/vllm-workspace/ray_init.sh leader --ray_cluster_size=$num_workers; 
                 python3 -m vllm.entrypoints.openai.api_server \
                  --tensor-parallel-size $num_workers \
                  --host 0.0.0.0 --port 8080 \
                  --model $model_id \
                  $extra"
          resources:
            requests:
              cpu: "$cpus"
              memory: "$memory"
              nvidia.com/gpu: "$gpus"
            limits:
              cpu: "$cpus"
              memory: "$memory"
              nvidia.com/gpu: "$gpus"
          ports:
          # if use 8080 as exposed port (if required)
          - containerPort: 8080
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 90
            periodSeconds: 30
    workerTemplate:
      spec:
        runtimeClassName: nvidia
        containers:
        - name: vllm-worker
          image: bundenth/ray-vllm:v1_1
          env:
            - name: HUGGING_FACE_HUB_TOKEN
              value: $hf_token
          command:
            - sh
            - -c
            - "/vllm-workspace/ray_init.sh worker --ray_address=$$LWS_LEADER_ADDRESS"
          resources:
            requests:
              cpu: "$cpus"
              memory: "$memory"
              nvidia.com/gpu: "$gpus"
            limits:
              cpu: "$cpus"
              memory: "$memory"
              nvidia.com/gpu: "$gpus"
