site_name: Kalavai Documentation
nav:
  - Getting started:
    - Welcome to Kalavai: index.md
    - Concepts: concepts.md
    - Getting started: getting_started.md
  - Create AI pools:
    - Local pools: local_pool.md
    - Public pools: public_pool.md
  - Community computing:
    - Petals swarm: petals.md
  - Applications: 
    - Templates: templates.md
    - Ray: ray.md
  # - Tutorials:
  #   - End 2 end example: end2end.md
  # - More:
  #   - FAQs: faqs.md
  #   - Managed: enterprise.md

theme:
  name: material
  navigation_depth: 3
  logo: assets/icons/logo_no_background.png
  favicon: assets/icons/browser.png
  features:
    - navigation.sections
    - navigation.instant
    - navigation.instant.progress
  palette:
  # Palette toggle for dark mode
    - scheme: default
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    # Palette toggle for light mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

markdown_extensions:
  - attr_list

plugins:
  - search
  - tags
  